export const FETCH_SECTIONS_PENDING = "sections/FETCH_SECTIONS_PENDING";
export const FETCH_SECTIONS_FULFILLED = "sections/FETCH_SECTIONS_FULFILLED";
export const FETCH_SECTIONS_REJECTED = "sections/FETCH_SECTIONS_REJECTED";
