export const FETCH_OUTQUOTES_PENDING = "outquotes/FETCH_OUTQUOTES_PENDING";
export const FETCH_OUTQUOTES_FULFILLED = "outquotes/FETCH_OUTQUOTES_FULFILLED";
export const FETCH_OUTQUOTES_REJECTED = "outquotes/FETCH_OUTQUOTES_REJECTED";
