export const FETCH_ARTICLES_PENDING = "articles/FETCH_ARTICLES_PENDING";
export const FETCH_ARTICLES_FULFILLED = "articles/FETCH_ARTICLES_FULFILLED";
export const FETCH_ARTICLES_REJECTED = "articles/FETCH_ARTICLES_REJECTED";

export const FETCH_AUTHORSHIPS_PENDING = "articles/FETCH_AUTHORSHIPS_PENDING";
export const FETCH_AUTHORSHIPS_FULFILLED =
  "articles/FETCH_AUTHORSHIPS_FULFILLED";
export const FETCH_AUTHORSHIPS_REJECTED = "articles/FETCH_AUTHORSHIPS_REJECTED";
