export const SEARCH_ARTICLES_PENDING = "articles/SEARCH_ARTICLES_PENDING";
export const SEARCH_ARTICLES_FULFILLED = "articles/SEARCH_ARTICLES_FULFILLED";
export const SEARCH_ARTICLES_REJECTED = "articles/SEARCH_ARTICLES_REJECTED";