export const FETCH_MEDIA_PENDING = 'media/FETCH_MEDIA_PENDING';
export const FETCH_MEDIA_REJECTED = 'media/FETCH_MEDIA_REJECTED';
export const FETCH_MEDIA_FULFILLED = 'media/FETCH_MEDIA_FULFILLED';
export const ADD_MEDIA = 'media/ADD_MEDIA';