export const REFRESH_WINDOW_DIMENSIONS = "core/REFRESH_WINDOW_DIMENSIONS";
export const OPEN_SIDEBAR = "core/OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "core/CLOSE_SIDEBAR";

export const FETCH_INIT_DATA_PENDING = "core/FETCH_INIT_DATA_PENDING";
export const FETCH_INIT_DATA_FULFILLED = "core/FETCH_INIT_DATA_FULFILLED";
export const FETCH_INIT_DATA_REJECTED = "core/FETCH_INIT_DATA_REJECTED";
