export const FETCH_USERS_PENDING = "users/FETCH_USERS_PENDING";
export const FETCH_USERS_REJECTED = "users/FETCH_USERS_REJECTED";
export const FETCH_USERS_FULFILLED = "users/FETCH_USERS_FULFILLED";

export const FETCH_USER_ROLES_PENDING = "users/FETCH_USER_ROLES_PENDING";
export const FETCH_USER_ROLES_REJECTED = "users/FETCH_USER_ROLES_REJECTED";
export const FETCH_USER_ROLES_FULFILLED = "users/FETCH_USER_ROLES_FULFILLED";

export const FETCH_ROLES_PENDING = "users/FETCH_ROLES_PENDING";
export const FETCH_ROLES_REJECTED = "users/FETCH_ROLES_REJECTED";
export const FETCH_ROLES_FULFILLED = "users/FETCH_ROLES_FULFILLED";
