export const SIGN_UP_PENDING = 'accounts/SIGN_UP_PENDING';
export const SIGN_UP_FULFILLED = 'accounts/SIGN_UP_FULFILLED';
export const SIGN_UP_REJECTED = 'accounts/SIGN_UP_REJECTED';

export const SIGN_IN_PENDING = 'accounts/SIGN_IN_PENDING';
export const SIGN_IN_FULFILLED = 'accounts/SIGN_IN_FULFILLED';
export const SIGN_IN_REJECTED = 'accounts/SIGN_IN_REJECTED';

export const SIGN_OUT_PENDING = 'accounts/SIGN_OUT_PENDING';
export const SIGN_OUT_FULFILLED = 'accounts/SIGN_OUT_FULFILLED';
export const SIGN_OUT_REJECTED = 'accounts/SIGN_OUT_REJECTED';

export const UPDATE_USER_PENDING = 'accounts/UPDATE_USER_PENDING';
export const UPDATE_USER_FULFILLED = 'accounts/UPDATE_USER_FULFILLED';
export const UPDATE_USER_REJECTED = 'accounts/UPDATE_USER_REJECTED';

export const OPEN_SIGN_IN_MODAL = 'accounts/OPEN_SIGN_IN_MODAL';
export const CLOSE_SIGN_IN_MODAL = 'accounts/CLOSE_SIGN_IN_MODAL';

export const OPEN_SUBSCRIPTION_MODAL = 'accounts/OPEN_SUBSCRIPTION_MODAL';
export const CLOSE_SUBSCRIPTION_MODAL = 'accounts/CLOSE_SUBSCRIPTION_MODAL';

export const CREATE_SUBSCRIBER_PENDING = 'accounts/CREATE_SUBSCRIBER_PENDING';
export const CREATE_SUBSCRIBER_FULFILLED = 'accounts/CREATE_SUBSCRIBER_FULFILLED';
export const CREATE_SUBSCRIBER_REJECTED = 'accounts/CREATE_SUBSCRIBER_REJECTED';

export const CREATE_SESSION = 'accounts/CREATE_SESSION';

export const VALIDATE_TOKEN_FULFILLED = 'accounts/VALIDATE_TOKEN_FULFILLED';
export const VALIDATE_TOKEN_REJECTED = 'accounts/VALIDATE_TOKEN_REJECTED';
