export const REFRESH_WINDOW_DIMENSIONS = 'core/REFRESH_WINDOW_DIMENSIONS';
export const OPEN_SIDEBAR = 'core/OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'core/CLOSE_SIDEBAR';
export const OPEN_LIGHTBOX = 'core/OPEN_LIGHTBOX';
export const CLOSE_LIGHTBOX = 'core/CLOSE_LIGHTBOX';
