export const CREATE_USER_PENDING = 'accounts/CREATE_USER_PENDING';
export const CREATE_USER_FULFILLED = 'accounts/CREATE_USER_FULFILLED';
export const CREATE_USER_REJECTED = 'accounts/CREATE_USER_REJECTED';