export const FETCH_NEWSPAPERS_PENDING = "newspapers/FETCH_NEWSPAPERS_PENDING";
export const FETCH_NEWSPAPERS_FULFILLED = "newspapers/FETCH_NEWSPAPERS_FULFILLED";
export const FETCH_NEWSPAPERS_REJECTED = "newspapers/FETCH_NEWSPAPERS_REJECTED";
